[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn mcp-hub.main:app --config gunicorn.conf.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3